spring:
  application:
    name: sgab-rest-api

  datasource:
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      url: jdbc:sqlserver://localhost:1433;databaseName=bd_bat;encrypt=false
      username: sa
      password: '@dminti35'
  jpa:
      hibernate:
          ddl-auto: none
      properties:
          hibernate:
      show_sql: false

      open-in-view: false